"""create user table

Revision ID: 30d8b9f3a90b
Revises:
Create Date: 2024-01-16 23:12:02.880540

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "30d8b9f3a90b"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create the schema if it doesn't exist
    op.execute("CREATE SCHEMA IF NOT EXISTS account")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=50), nullable=False),
        sa.Column("phone", sa.String(length=50), nullable=False),
        sa.Column("password", sa.String(length=100), nullable=False),
        sa.Column("role", sa.Integer(), nullable=False),
        sa.Column("gender", sa.Integer(), nullable=True),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("last_login", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        schema="account",
    )
    op.create_index(
        op.f("ix_account_users_id"), "users", ["id"], unique=False, schema="account"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # Drop the table first
    op.drop_table("users", schema="account")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_account_users_id"), table_name="users", schema="account")
    op.drop_table("users", schema="account")
    # ### end Alembic commands ###
